services:
  web:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    # tty: true
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev --name init && npm run dev -- --host"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
    restart: unless-stopped
